name: Deploy Serverless on Push
run-name: ${{ github.actor }} is deploying the backend app
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of the branch is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Adding dependency
        run: |
          composer install --no-dev
      - name: Adding serverless package
        run: |
          npm install -g serverless
      - name: configuring serverless
        run: |
          serverless config credentials --provider aws --key ${{ secrets.AWS_KEY_ID }} --secret ${{ secrets.AWS_KEY_SECRET }}
      - name: Decrypt Env file
        run: |
          php artisan env:decrypt --key=${{ secrets.ENV_DECRYPT_KEY }}
      - name: Migration of table if required
        run: |
          php artisan migrate
      - name: config clear
        run: |
          php artisan optimize:clear
      - name: serverless deploy of the project
        run: |
          serverless deploy
      - run: echo "This job's status is ${{ job.status }}."


